version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/stockpilot
      NEXTAUTH_SECRET: dev-secret-min-32-chars-please-change
      NEXTAUTH_URL: http://localhost:3000
      REDIS_URL: redis://redis:6379
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"
