"use client";

import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { PageHeader } from "@/components/dashboard/shared";

type Channel = { id: string; name: string; type: string; active: boolean; lastSyncAt: string | null };

const CHANNEL_TYPES = ["SHOPIFY", "ETSY", "AMAZON", "EBAY", "MANUAL"] as const;
type ChannelType = (typeof CHANNEL_TYPES)[number];

const CREDENTIAL_FIELDS: Record<ChannelType, Array<{ key: string; label: string; placeholder?: string }>> = {
  SHOPIFY: [
    { key: "shop", label: "Shop domain", placeholder: "mystore.myshopify.com" },
    { key: "access_token", label: "Admin API access token", placeholder: "shpat_..." },
    { key: "webhook_secret", label: "Webhook secret", placeholder: "Generated by Shopify" },
  ],
  ETSY: [
    { key: "api_key", label: "API key", placeholder: "Etsy API key" },
    { key: "shop_id", label: "Shop ID", placeholder: "Etsy shop ID" },
  ],
  AMAZON: [
    { key: "seller_id", label: "Seller ID", placeholder: "Amazon seller ID" },
    { key: "marketplace_id", label: "Marketplace ID", placeholder: "e.g. ATVPDKIKX0DER" },
    { key: "refresh_token", label: "LWA refresh token", placeholder: "Amzn1.oauth2..." },
  ],
  EBAY: [
    { key: "client_id", label: "Client ID", placeholder: "eBay app client ID" },
    { key: "client_secret", label: "Client secret", placeholder: "eBay app client secret" },
    { key: "refresh_token", label: "User token (refresh)", placeholder: "v^1.1#i^1#r^..." },
  ],
  MANUAL: [],
};

const STATUS_COLORS: Record<string, string> = {
  SHOPIFY: "bg-green-100 text-green-800 dark:bg-green-900/40 dark:text-green-300",
  ETSY: "bg-orange-100 text-orange-800 dark:bg-orange-900/40 dark:text-orange-300",
  AMAZON: "bg-yellow-100 text-yellow-800 dark:bg-yellow-900/40 dark:text-yellow-300",
  EBAY: "bg-blue-100 text-blue-800 dark:bg-blue-900/40 dark:text-blue-300",
  MANUAL: "bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-300",
};

export default function ChannelSettingsPage() {
  const [channels, setChannels] = useState<Channel[]>([]);
  const [message, setMessage] = useState("");
  const [showForm, setShowForm] = useState(false);
  const [saving, setSaving] = useState(false);
  const [selectedType, setSelectedType] = useState<ChannelType>("SHOPIFY");
  const [name, setName] = useState("");
  const [creds, setCreds] = useState<Record<string, string>>({});

  useEffect(() => {
    fetch("/api/channels").then((res) => res.json()).then(setChannels);
  }, []);

  function handleTypeChange(type: ChannelType) {
    setSelectedType(type);
    setCreds({});
  }

  async function handleCreate(e: React.FormEvent) {
    e.preventDefault();
    setSaving(true);
    try {
      const res = await fetch("/api/channels", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ name, type: selectedType, credentials: creds, active: true }),
      });
      if (!res.ok) {
        const err = await res.json();
        setMessage(`Error: ${JSON.stringify(err.error)}`);
        return;
      }
      const created = await res.json();
      setChannels((prev) => [created, ...prev]);
      setShowForm(false);
      setName("");
      setCreds({});
      setMessage(`Channel "${created.name}" created successfully.`);
    } finally {
      setSaving(false);
    }
  }

  async function patchChannel(id: string, payload: Partial<Channel>) {
    const res = await fetch(`/api/channels/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });
    const data = await res.json();
    setChannels((prev) => prev.map((ch) => (ch.id === id ? { ...ch, ...data } : ch)));
  }

  const fields = CREDENTIAL_FIELDS[selectedType];

  return (
    <div className="space-y-6 p-6">
      <PageHeader
        back={{ href: "/dashboard/settings", label: "Settings" }}
        title="Channels"
        description="Connect and manage your sales channels."
        action={
          <Button onClick={() => { setShowForm((v) => !v); setMessage(""); }}>
            {showForm ? "Cancel" : "+ Add Channel"}
          </Button>
        }
      />

      {message && (
        <Card>
          <CardContent className="p-4 text-sm">{message}</CardContent>
        </Card>
      )}

      {showForm && (
        <Card>
          <CardContent className="p-6">
            <h3 className="mb-4 text-base font-semibold">New Channel</h3>
            <form onSubmit={handleCreate} className="space-y-4">
              <div className="space-y-2">
                <Label>Channel type</Label>
                <div className="flex flex-wrap gap-2">
                  {CHANNEL_TYPES.map((t) => (
                    <button
                      key={t}
                      type="button"
                      onClick={() => handleTypeChange(t)}
                      className={`rounded-full border-2 px-4 py-1 text-sm font-medium transition ${
                        selectedType === t
                          ? "border-foreground bg-foreground text-background"
                          : "border-border bg-transparent hover:border-foreground"
                      }`}
                    >
                      {t}
                    </button>
                  ))}
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="ch-name">Display name</Label>
                <Input
                  id="ch-name"
                  required
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  placeholder={`e.g. My ${selectedType} Store`}
                />
              </div>

              {fields.map((f) => (
                <div key={f.key} className="space-y-2">
                  <Label htmlFor={`cred-${f.key}`}>{f.label}</Label>
                  <Input
                    id={`cred-${f.key}`}
                    value={creds[f.key] ?? ""}
                    onChange={(e) => setCreds((prev) => ({ ...prev, [f.key]: e.target.value }))}
                    placeholder={f.placeholder}
                  />
                </div>
              ))}

              {selectedType === "SHOPIFY" && (
                <div className="rounded-lg bg-muted/60 p-3 text-xs text-muted-foreground">
                  <strong>Webhook endpoint:</strong>{" "}
                  <code className="font-mono">POST /api/webhooks/shopify</code>
                  <br />
                  Register this URL in your Shopify admin under <em>Settings → Notifications → Webhooks</em> for the{" "}
                  <em>orders/create</em> topic. Use the webhook secret above to verify payloads.
                </div>
              )}

              <div className="flex justify-end gap-2 pt-2">
                <Button type="button" variant="outline" onClick={() => setShowForm(false)}>
                  Cancel
                </Button>
                <Button type="submit" disabled={saving}>
                  {saving ? "Creating…" : "Create Channel"}
                </Button>
              </div>
            </form>
          </CardContent>
        </Card>
      )}

      <div className="grid gap-4">
        {channels.length === 0 && !showForm && (
          <p className="text-sm text-muted-foreground">No channels yet. Click "+ Add Channel" to connect one.</p>
        )}
        {channels.map((channel) => (
          <Card key={channel.id}>
            <CardContent className="flex flex-col gap-3 p-4 md:flex-row md:items-center md:justify-between">
              <div className="flex items-center gap-3">
                <span className={`rounded-full px-2.5 py-0.5 text-xs font-semibold ${STATUS_COLORS[channel.type] ?? STATUS_COLORS.MANUAL}`}>
                  {channel.type}
                </span>
                <div>
                  <p className="font-medium">{channel.name}</p>
                  <p className="text-sm text-muted-foreground">
                    Last sync: {channel.lastSyncAt ? new Date(channel.lastSyncAt).toLocaleString() : "Never"} ·{" "}
                    <span className={channel.active ? "text-green-600 dark:text-green-400" : "text-red-500"}>
                      {channel.active ? "Connected" : "Disconnected"}
                    </span>
                  </p>
                </div>
              </div>
              <div className="flex gap-2">
                <Button variant="outline" onClick={() => patchChannel(channel.id, { active: !channel.active })}>
                  {channel.active ? "Disconnect" : "Connect"}
                </Button>
                <Button
                  variant="outline"
                  onClick={() => {
                    patchChannel(channel.id, { lastSyncAt: new Date().toISOString() as never });
                    setMessage(`Sync triggered for ${channel.name}.`);
                  }}
                >
                  Sync Now
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
