"use client";

import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { PageHeader } from "@/components/dashboard/shared";

type Printer = { id: string; name: string; purpose: string; connectionType: string; ipAddress: string | null; bluetoothDeviceId: string | null; active: boolean };
const emptyPrinter = { id: "", name: "", purpose: "SKU_LABEL", connectionType: "NETWORK", ipAddress: "", bluetoothDeviceId: "", active: true };

export default function PrinterSettingsPage() {
  const [printers, setPrinters] = useState<Printer[]>([]);
  const [editing, setEditing] = useState<typeof emptyPrinter | null>(null);
  useEffect(() => { fetch("/api/printer-configs").then((res) => res.json()).then(setPrinters); }, []);
  async function savePrinter() { if (!editing) return; const response = await fetch(editing.id ? `/api/printer-configs/${editing.id}` : "/api/printer-configs", { method: editing.id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(editing) }); const data = await response.json(); setPrinters((prev) => editing.id ? prev.map((printer) => printer.id === data.id ? data : printer) : [...prev, data]); setEditing(null); }
  return <div className="space-y-6 p-6"><PageHeader title="Printers" description="Manage label printers and default routing." action={<Button onClick={() => setEditing(emptyPrinter)}>Add Printer</Button>} /><div className="grid gap-4">{printers.map((printer) => <Card key={printer.id}><CardContent className="flex flex-col gap-3 p-4 md:flex-row md:items-center md:justify-between"><div><p className="font-medium">{printer.name}</p><p className="text-sm text-muted-foreground">{printer.purpose} · {printer.connectionType}</p></div><Button variant="outline" onClick={() => setEditing({ id: printer.id, name: printer.name, purpose: printer.purpose, connectionType: printer.connectionType, ipAddress: printer.ipAddress ?? "", bluetoothDeviceId: printer.bluetoothDeviceId ?? "", active: printer.active })}>Edit</Button></CardContent></Card>)}</div>{editing ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><Card className="w-full max-w-xl"><CardContent className="grid gap-4 p-6 md:grid-cols-2"><Input value={editing.name} onChange={(e) => setEditing((prev) => prev ? { ...prev, name: e.target.value } : prev)} placeholder="Printer name" /><select value={editing.purpose} onChange={(e) => setEditing((prev) => prev ? { ...prev, purpose: e.target.value } : prev)} className="h-10 rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="SKU_LABEL">SKU Label</option><option value="SHIPPING_LABEL">Shipping Label</option><option value="BOTH">Both</option></select><select value={editing.connectionType} onChange={(e) => setEditing((prev) => prev ? { ...prev, connectionType: e.target.value } : prev)} className="h-10 rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="NETWORK">Network</option><option value="BLUETOOTH">Bluetooth</option><option value="USB_DIRECT">USB Direct</option></select><Input value={editing.ipAddress} onChange={(e) => setEditing((prev) => prev ? { ...prev, ipAddress: e.target.value } : prev)} placeholder="IP address" /><Input value={editing.bluetoothDeviceId} onChange={(e) => setEditing((prev) => prev ? { ...prev, bluetoothDeviceId: e.target.value } : prev)} placeholder="Bluetooth device ID" className="md:col-span-2" /><div className="md:col-span-2 flex justify-end gap-2"><Button variant="outline" onClick={() => setEditing(null)}>Cancel</Button><Button onClick={savePrinter}>Save</Button></div></CardContent></Card></div> : null}</div>;
}
